name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]
    name: Java ${{ matrix.java }} setup

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1

        with:
          java-version: ${{ matrix.java }}

      - name: Build
        run: ./gradlew classes

      - name: Codestyle
        run: ./gradlew spotlessCheck

      - name: Test
        if: matrix.java == '11'
        run: ./gradlew test jacocoTestReport
        env:
          API_KEY: ${{ secrets.ETHERSCAN_API_KEY_1 }}

      - name: Test
        if: matrix.java == '17'
        run: ./gradlew test jacocoTestReport
        env:
          API_KEY: ${{ secrets.ETHERSCAN_API_KEY_2 }}

      - name: SonarQube
        if: matrix.java == '17'
        run: ./gradlew sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
